datasets:
  dataset_name: WikipediaPlainText
  dataset_raw_path: basemodel/data/raw/AllCombined.txt
  dataset_tokenize_path: basemodel/data/raw/sent_tokenize_text.txt
  dataset_processed_path: basemodel/data/processed/
  max_dataset: 50000

tokenizer:
  merges_path: basemodel/models/tokenizer/merges.json
  vocab_path: basemodel/models/tokenizer/vocab.json
  vocab_size: 10887

models:
  max_len: 128
  batch_size: 32
  mask_prob: 0.15
  n_heads: 8
  embed_dim: 256
  dropout: 0.1
  n_blocks: 6
  early_stopping_patience: 5
  early_stopping: true
  learning_rate: 0.001
  model_save_path: basemodel/models/checkpoints

  epochs: 5000
  eval_interval: 500