datasets:
  dataset_name: WikipediaPlainText
  dataset_raw_path: basemodel/data/raw/AllCombined.txt
  dataset_tokenize_path: basemodel/data/raw/sent_tokenize_text.txt
  dataset_processed_path: basemodel/data/processed/corpus.bin
  max_dataset: 50000

tokenizer:
  merges_path: basemodel/models/tokenizer/merges.json
  vocab_path: basemodel/models/tokenizer/vocab.json
  vocab_size: 10887